export const PLAGIARISM_CONFIG = {
  maxTextLength: 10000,
  ngramSize: 3,
  minDuplicateLength: 8,
  minMatchLength: 6,
  minBlockLength: 16,
  contextBefore: 20,
  contextAfter: 20,
  maxSourceGap: 8,
  maxTargetGap: 8,
  minDensity: 0.15,
  minScore: 0.5,
  lengthScoreWeight: 0.7,
  densityScoreWeight: 0.3,
  defaultThreshold: 0.6,
  minThreshold: 0,
  maxThreshold: 1,
  defaultEditDistance: 2,
  minEditDistance: 0,
  jaccardWeight: 0.5,
  simHashWeight: 0.2,
  duplicateRateWeight: 0.3,
  simHashBits: 64,
  contextRadius: 24,
} as const;
